type AstroEvent = {
  astroEvent: string;
  astroTime: string;
  astroTitle: string;
  locdate: string;
  seq: number;
};

type AstroEvents = {
  [month: string]: AstroEvent[];
};

export const AstroEventsDummy: AstroEvents = {
  "202410": [
    {
      astroEvent: "올해 가장 큰 달은 10월 17일 밤에 뜨는 달이다. 달이 더 크게 보이는 원리는 망(望)인 동시에 달이 근지점을 통과해 달과 지구의 거리가 최소가 되기 때문이다. 10월 17일 달은 서울 기준 17시 38분에 떠서 18일 7시 22분에 진다. 10월 17일 지구와 달의 거리는 약 357,200km로 지구 - 달 평균 거리인 384,400km 보다 27,200km 이상 가깝다.",
      astroTime: "",
      astroTitle: "10월 17일 올해 가장 큰 달",
      locdate: "202410",
      seq: 1,
    },
    {
      astroEvent: "수성의 외합",
      astroTime: "06:00",
      astroTitle: "",
      locdate: "20241001",
      seq: 1,
    },
    {
      astroEvent: "합삭",
      astroTime: "03:49",
      astroTitle: "",
      locdate: "20241003",
      seq: 1,
    },
    {
      astroEvent: "달의 원지점(406,500km)",
      astroTime: "04:39",
      astroTitle: "",
      locdate: "20241003",
      seq: 2,
    },
    {
      astroEvent: "상현달",
      astroTime: "03:55",
      astroTitle: "",
      locdate: "20241011",
      seq: 1,
    },
    {
      astroEvent: "달과 토성의 근접(1.0°)",
      astroTime: "03:05",
      astroTitle: "",
      locdate: "20241015",
      seq: 1,
    },
    {
      astroEvent: "망",
      astroTime: "20:26",
      astroTitle: "",
      locdate: "20241017",
      seq: 1,
    },
    {
      astroEvent: "달과 플레이아데스 성단의 근접(0.1°)",
      astroTime: "04:59",
      astroTitle: "",
      locdate: "20241020",
      seq: 1,
    },
    {
      astroEvent: "달과 폴룩스의 근접(1.8°)",
      astroTime: "02:16",
      astroTitle: "",
      locdate: "20241024",
      seq: 1,
    },
    {
      astroEvent: "달과 화성의 근접(4.2°)",
      astroTime: "04:55",
      astroTitle: "",
      locdate: "20241024",
      seq: 2,
    },
    {
      astroEvent: "하현달",
      astroTime: "17:03",
      astroTitle: "",
      locdate: "20241024",
      seq: 3,
    },
    {
      astroEvent: "달과 벌집 성단의 근접(3.3°)",
      astroTime: "02:35",
      astroTitle: "",
      locdate: "20241025",
      seq: 1,
    },
    {
      astroEvent: "달의 원지점(406,200km)",
      astroTime: "07:50",
      astroTitle: "",
      locdate: "20241030",
      seq: 1,
    },
  ],
  "202411": [
    {
      astroEvent: "한국천문연구원이 개발한 달 우주환경 모니터(LUSEM)는 고에너지 입자를 검출할 수 있는 센서로서, 미국의 무인 달 착륙선 Nova-C에 탑재되어 임무를 수행할 예정이다. LUSEM은 발사 후 달까지 가는 동안 근지구 공간의 우주환경을 조사하고, 달 궤도 도착 후 착륙지로 하강하며 관측을 수행하며, 착륙 후에는 달 표면의 라이너 감마(Reiner Gamma) 지역에서 관측할 예정이다. LUSEM의 관측자료는 달에서의 우주 풍화 현상과 심우주로부터 날아오는 고에너지 입자를 이해하는 데 기여할 것이다.",
      astroTime: "",
      astroTitle: "달 우주환경 모니터(LUSEM)",
      locdate: "202411",
      seq: 1,
    },
    {
      astroEvent: "합삭",
      astroTime: "21:47",
      astroTitle: "",
      locdate: "20241101",
      seq: 1,
    },
    {
      astroEvent: "상현달",
      astroTime: "14:55",
      astroTitle: "",
      locdate: "20241109",
      seq: 1,
    },
    {
      astroEvent: "달의 근지점(360,100 km)",
      astroTime: "20:16",
      astroTitle: "",
      locdate: "20241114",
      seq: 1,
    },
    {
      astroEvent: "망",
      astroTime: "06:28",
      astroTitle: "",
      locdate: "20241116",
      seq: 1,
    },
    {
      astroEvent: "수성의 동방최대이각(23°)",
      astroTime: "17:00",
      astroTitle: "",
      locdate: "20241116",
      seq: 2,
    },
    {
      astroEvent: "달과 화성의 근접(2.6°)",
      astroTime: "06:07",
      astroTitle: "",
      locdate: "20241121",
      seq: 1,
    },
    {
      astroEvent: "달과 레굴루스의 근접(3°)",
      astroTime: "05:48",
      astroTitle: "",
      locdate: "20241123",
      seq: 1,
    },
    {
      astroEvent: "달의 원지점(405,300 km)",
      astroTime: "20:56",
      astroTitle: "",
      locdate: "20241126",
      seq: 1,
    },
  ],
  "202412": [
    {
      astroEvent: "태양-지구-행성의 순서로 위치한 때를 행성이 충의 위치에 있다고 한다. 충일 때 그 행성이 지구와 가장 가깝게 위치하고 밝게 빛나는 관측의 최적기라 할 수 있다. 12월 8일은 목성을 가장 잘 볼 수 있는 날로, -2.8 등급의 밝은 목성을 관측할 수 있다.",
      astroTime: "",
      astroTitle: "12월 8일 목성의 충",
      locdate: "202412",
      seq: 1,
    },
    {
      astroEvent: "화성과 벌집 성단의 근접(1.6°)",
      astroTime: "21:08",
      astroTitle: "",
      locdate: "20241203",
      seq: 1,
    },
    {
      astroEvent: "목성의 충",
      astroTime: "06:00",
      astroTitle: "",
      locdate: "20241208",
      seq: 1,
    },
    {
      astroEvent: "화성 유(동-서)",
      astroTime: "06:00",
      astroTitle: "",
      locdate: "20241208",
      seq: 2,
    },
    {
      astroEvent: "달과 토성의 근접(0.3°)",
      astroTime: "17:49",
      astroTitle: "",
      locdate: "20241208",
      seq: 3,
    },
    {
      astroEvent: "해왕성 유(서-동)",
      astroTime: "20:00",
      astroTitle: "",
      locdate: "20241208",
      seq: 4,
    },
    {
      astroEvent: "상현달",
      astroTime: "00:27",
      astroTitle: "",
      locdate: "20241209",
      seq: 1,
    },
    {
      astroEvent: "달의 근지점(365,400km)",
      astroTime: "22:20",
      astroTitle: "",
      locdate: "20241212",
      seq: 1,
    },
    {
      astroEvent: "달과 플레이아데스 성단의 근접(0.1°)",
      astroTime: "02:13",
      astroTitle: "",
      locdate: "20241214",
      seq: 1,
    },
    {
      astroEvent: "망",
      astroTime: "18:02",
      astroTitle: "",
      locdate: "20241215",
      seq: 1,
    },
    {
      astroEvent: "수성 유(서-동)",
      astroTime: "06:00",
      astroTitle: "",
      locdate: "20241216",
      seq: 1,
    },
    {
      astroEvent: "달과 폴룩스의 근접(2.1°)",
      astroTime: "21:12",
      astroTitle: "",
      locdate: "20241217",
      seq: 1,
    },
    {
      astroEvent: "달과 벌집 성단의 근접(2.8°)",
      astroTime: "20:28",
      astroTitle: "",
      locdate: "20241218",
      seq: 1,
    },
    {
      astroEvent: "작은곰자리 유성우 극대(ZHR=10)",
      astroTime: "19:00",
      astroTitle: "",
      locdate: "20241222",
      seq: 1,
    },
    {
      astroEvent: "하현달",
      astroTime: "07:18",
      astroTitle: "",
      locdate: "20241223",
      seq: 1,
    },
    {
      astroEvent: "달과 스피카의 근접(0.2°)",
      astroTime: "04:28",
      astroTitle: "",
      locdate: "20241225",
      seq: 1,
    },
    {
      astroEvent: "합삭",
      astroTime: "07:27",
      astroTitle: "",
      locdate: "20241231",
      seq: 1,
    },
  ],
};