spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: "true"
        use_sql_comments: "true"
        show_sql: "true"
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

kakao:
  auth:
    uri: ${KAKAO_AUTH_URI}
  api:
    uri: ${KAKAO_API_URI}
  client:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
  redirect:
    uri:
      login: ${KAKAO_REDIRECT_URI_LOGIN}
      logout: ${KAKAO_REDIRECT_URI_LOGOUT}
      client: ${KAKAO_REDIRECT_URI_CLIENT}
  response:
    type: ${KAKAO_RESPONSE_TYPE}
  grant:
    type: ${KAKAO_GRANT_TYPE}

base:
  profile-image: ${BASE_PROFILE_IMAGE}
  server-domain: ${SERVER_DOMAIN}

server:
  port: ${SERVER_PORT}
